AllCops:
  RunRailsCops: true
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Rakefile'
    - 'zeus.rb'
    - 'Guardfile'
    - 'config/application.rb'
    - 'config/initializers/**/*'

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120
  EOF