default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host:     <%= ENV['DB_HOST'] %>
  port:     <%= ENV['DB_PORT'] %>
  username: postgres
  database: service-workers-rails_development

test:
  <<: *default
  host:     <%= ENV['DB_HOST'] %>
  port:     <%= ENV['DB_PORT'] %>
  username: postgres
  database: service-workers-rails_test

production:
  url: <%= ENV['DATABASE_URL'] %>